### ISSUE TITLE
IBMQ.enable_account(..) tries to instantiate a deprecated simulator when discovering backends

### ISSUE THREAD

**Issue by ishapoval** [Qiskit/qiskit-metapackage#184]
### Informations

- **Qiskit version**: 0.8.0
- **Python version**: 3.6.7
- **Operating system**: Ubuntu 18.04

### What is the current behavior?
Remote backend "ibmqx_qasm_simulator" could not be instantiated due to an invalid config: {'backend_version': ['Missing data for required field.'], 'gates': {0: {'name': ['Missing data for required field.'], 'parameters': ['Missing data for required field.'], 'qasm_def': ['Missing data for required field.']}}, 'local': ['Missing data for required field.'], 'max_shots': ['Missing data for required field.'], 'open_pulse': ['Missing data for required field.'], 'basis_gates': ['Missing data for required field.'], 'n_qubits': ['Missing data for required field.'], 'conditional': ['Missing data for required field.'], 'backend_name': ['Missing data for required field.'], 'memory': ['Missing data for required field.']}

### Steps to reproduce the problem

from qiskit import IBMQ
IBMQ.enable_account(token='MYTOKEN')

### What is the expected behavior?
No attempts to instantiate a deprecated simulator.

**Comment by ajavadia** [comment]
Hi, I think this problem is resolved. The next release should be fixed. @diego-plan9 can you confirm?

**Comment by diego-plan9** [comment]
I think the original report (regarding the `ibmqx_qasm_simulator` at that point in time) has indeed been resolved - it was likely a temporary hiccup, as qiskit was unable to understand what the API was returning for that particular backend. 

I'm closing accordingly - please reopen if you are still encountering this problem.

**Comment by ishapoval** [comment]
Thanks, but the problem is still there even for the latest-greatest Qiskit 0.10.4. The bug is too enduring to be a "temporary hiccup".. :)

**Comment by ajavadia** [comment]
@ishapoval can you paste the output you are seeing?

**Comment by ishapoval** [comment]
It's still the one originally reported:

> Remote backend "ibmqx_qasm_simulator" could not be instantiated due to an invalid config: {'backend_name': ['Missing data for required field.'], 'basis_gates': ['Missing data for required field.'], 'open_pulse': ['Missing data for required field.'], 'n_qubits': ['Missing data for required field.'], 'max_shots': ['Missing data for required field.'], 'memory': ['Missing data for required field.'], 'conditional': ['Missing data for required field.'], 'local': ['Missing data for required field.'], 'backend_version': ['Missing data for required field.'], 'gates': {0: {'name': ['Missing data for required field.'], 'parameters': ['Missing data for required field.'], 'qasm_def': ['Missing data for required field.']}}}

**Comment by ishapoval** [comment]
Qiskit 0.11 has the same problem. Please reopen the issue.
